[theme]
base = "light"
primaryColor = "#2159a6"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e0ecff"
textColor = "#222222"
linkColor = "#206cd6"
linkUnderline = true
codeBackgroundColor = "#f0f2f6"
font = "sans-serif"
baseFontSize = 16
baseFontWeight = 400
headingFont = "sans-serif"
headingFontSizes = ["2.75rem", "2.25rem", "1.75rem", "1.5rem", "1.25rem", "1rem"]
headingFontWeights = [700, 600, 600, 600, 600, 600]
codeFont = "monospace"
codeFontSize = "0.875rem"
codeFontWeight = 400
baseRadius = "8px"
buttonRadius = "8px"
borderColor = "#cccccc"
dataframeBorderColor = "#2159a6"
dataframeHeaderBackgroundColor = "#e0ecff"
showWidgetBorder = true
showSidebarBorder = true
chartCategoricalColors = [
    "#0068c9", "#83c9ff", "#ff2b2b", "#ffabab", "#29b09d",
    "#7defa1", "#ff8700", "#ffd16a", "#6d3fc0", "#d5dae5"
]
chartSequentialColors = [
    "#e4f5ff", "#c7ebff", "#a6dcff", "#83c9ff", "#60b4ff",
    "#3d9df3", "#1c83e1", "#0068c9", "#0054a3", "#004280"
]
